### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by marado** [robinflyhigh/Drupal2Wordpress#3]
Please add a license to this. I would of course prefer if it was a Free Software Licence, but even if you don't want this as free software, it would be great to know what can we count with as users of the software. 
In particular, there are a couple of forks of this repo already, but without a license permiting them to do so...

Thanks

**Comment by robinflyhigh** [comment]
@marado Added

**Comment by marado** [comment]
Thanks!

**Comment by robinflyhigh** [comment]
Thanks to you for bringing it to my notice :)

On 4/9/2015 8:37 PM, Marcos Marado wrote:
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/robinflyhigh/Drupal2Wordpress/issues/3#issuecomment-91257977>.
>

-- 
Regards,
Robin Singh
http://robinsingh.name
http://about.me/robin.singh
