### ISSUE TITLE
Permalinks

### ISSUE THREAD

**Issue by schobbent** [robinflyhigh/Drupal2Wordpress#5]
Hello,

I've a problem with the generated permalink from alias.

When I watch a post, on the wordpress website, it say it doesn't exit. 

But when I update the post, i don't have the same url but I can access the post.

Drupal v 7.1
Wordpres 4.1
My permalink settings are %postname%

Can you help me please?

**Comment by robinflyhigh** [comment]
@schobbent Can you share your site  url?

**Comment by robinflyhigh** [comment]
Closing as there is no response.
