### ISSUE TITLE
Database service unavailable

### ISSUE THREAD

**Issue by johnwarne** [robinflyhigh/Drupal2Wordpress#6]
Hey there, would love to try out this script, but I'm stopped dead in my tracks by the "This *database_name* service is UNAVAILABLE" error message. I've got the correct credentials in both the Wordpress and Drupal sections, yet I can't make either of those connections work. Could this perhaps be a MySQL configuration issue?

**Comment by robinflyhigh** [comment]
@johnwarne Can you share the url or config file?

**Comment by johnwarne** [comment]
Ugh, sorry for this non-issue. It WAS an issue with my MySQL configuration; the Drupal2Wordpress script worked fantastically. Thanks!

**Comment by robinflyhigh** [comment]
No worries @johnwarne
